[workspace]
members = ["shared", "server", "client"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
ash = "0.37" # Untuk akses Vulkan API langsung (Raw bindings)
